#ifndef __TRANSFORMATIONEVENT_H__
#define __TRANSFORMATIONEVENT_H__

enum class TRANSFORMATIONEVENT
{
	MOVE_LEFT,
	MOVE_RIGHT,
	ROTATE_RIGHT,
	ROTATE_UP,
	ROTATE_LEFT,
	ROTATE_DOWN,
	MOVE_FORWARD,
	MOVE_BACKWARDS,
};
#endif
